### ISSUE TITLE
14si2o_Flint - Auction winnings are stuck in the contract when oldBidder == address(0) while the license has not yet been minted

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-radicalxchange-judging#28]
14si2o_Flint

high

# Auction winnings are stuck in the contract when oldBidder == address(0) while the license has not yet been minted

## Summary

The `l.initialBidder` variable can be set to `address(0)` when there is no previous bidder. This is a valid input confirmed by the protocol team in the public discord. 

In `_closeAuction`, if the license has not yet been minted (which is a valid path confirmed by documentation and code), then `oldBidder = l.initialBidder`.

This case will happen very often when a artist sets up an auction for a new NFT collection. He will set initialBidder to `address(0)` since there is no previous bidder and he will set the minting of the license conditional on the successful closure of the auction (minting happens through `triggerTransfer`) to avoid gas costs.

The highest bid will be added to `l.availableCollateral[oldBidder]`, which in this case is `address(0)`.

As a consequence, the artist receives nothing and the collateral from the highest bid is locked in the contract. 

## Vulnerability Detail

The `l.initialBidder` can be set during initialization to the address of an initial bidder, or `address(0)` if there is no true initial bidder. The protocol team confirmed in the **public Discord** that this is a valid and sometimes expected value.
![image](https://github.com/sherlock-audit/2024-02-radicalxchange-14si2o/assets/111807030/9733ebbe-41f1-4463-ba1e-366f03ca4e14)

So whenever an artist wishes to put a new collection up for auction, it is very often the case that  `l.initialBidder = address(0)`;

  
When we look at the `_closeAuction` function, we find the below `if` statement

```solidity
       address oldBidder;
        if (IStewardLicense(address(this)).exists(tokenId)) {
            oldBidder = IStewardLicense(address(this)).ownerOf(tokenId);
        } else {
            oldBidder = l.initialBidder;
        }
```
If this resolves to `false`, then `oldBidder` will be set to `address(0)` in the aforementioned scenario.

When does this happen? The protocol allows artists to delay the minting of the license until the end of the auction. This is documented [here](https://pco-art-docs.vercel.app/for-artists/instantiating-your-art/). If an artist decides to do this, then the minting will only happen when the `triggerTransfer` function is called at the very end of `_closeAction`.

In `StewardLicenseInternal: _triggerTransfer`
```solidity
    function _triggerTransfer(
        address from,
        address to,
        uint256 tokenId
    ) internal {
        if (!_exists(tokenId)) {
            // Mint token
            _mint(to, tokenId);
        } else {
            // Safe transfer is not needed. If receiver does not implement ERC721Receiver, next auction can still happen. This prevents a failed transfer from locking up license
            _transfer(from, to, tokenId);
        }
    }

```
So when a artist delays minting and sets no initial bidder, then `oldBidder = address(0)`

This leads to a critical issue in the below line in `_closeAuction`

```solidity
            // Transfer bid to previous bidder's collateral
            l.availableCollateral[oldBidder] += l.highestBids[tokenId][currentAuctionRound].bidAmount;
            l.highestBids[tokenId][currentAuctionRound].collateralAmount = 0;
            l.bids[tokenId][currentAuctionRound][l.highestBids[tokenId][currentAuctionRound].bidder].collateralAmount = 0;
```
The `bidAmount` of the highest bidder is added to the `l.availableCollateral[oldBidder]`. But since oldBidder is address(0) in this scenario, the bidAmount is lost and the collateral sent by the bidder is permanently stuck in the contract. 

## Impact

The winnings of the auction are stuck in the contract with no way of getting it out. 
The artist who put his art up for auction receives nothing. 

## Code Snippet
https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/auction/EnglishPeriodicAuctionInternal.sol#L472-L477

https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/auction/EnglishPeriodicAuctionInternal.sol#L463-L534

https://github.com/sherlock-audit/2024-02-radicalxchange/blob/main/pco-art/contracts/license/StewardLicenseInternal.sol#L94-L108

## Tool used

Manual Review

## Recommendation

The `initialBidder` has extremely little use in the protocol. I would suggest removing it and replacing `initialBidder` with `repossessor` in `_closeAuction`. Assuming the repossessor is the artist or at least the owner, the winnings will always be sent to the correct person in above described scenario.

**Comment by 14si2o** [comment]
Escalate

This represents a clear loss of funds in a very common scenario.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This represents a clear loss of funds in a very common scenario. 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by ABDuullahi** [comment]
Escalate

on his behalf.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> on his behalf.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by gravenp** [comment]
The artist/owner is trusted and responsible for setting the initial bidder at creation (typically their own address or another chosen beneficiary). If they set it to 0 this scenario will play out as described, but according to Sherlock judging rule VII.3 - Zero address checks are not valid issues: https://docs.sherlock.xyz/audits/judging/judging

**Comment by 14si2o** [comment]
The rule you are quoting concerns checks against **accidental setting** of address(0) by a user or admin. That is not the case here. 

It is expected, valid and common behavior that collection owners will set the initialBidder to address(0). The protocol themselves confirmed this. And in the common case where they delayed minting until the end of the auction, they will lose all their profits.  

So this represents a direct loss as a result of **normal, accepted valid** behavior. In which case the rule you quote does not apply.

**Comment by gravenp** [comment]
I work on the protocol, and it is not expected/intended for the collection owner to set the initialBidder to 0. Can you point me to where that was stated?

**Comment by 14si2o** [comment]
Certainly. 

When you look at the finding, under vulnerability detail you have the screenshot of st4rgard3n, who confirmed in the public discord the 20th of March that: 

- initialBidder_ is either set during the initialization of the auction by a call to initializeAuction on the auction facet - if there is an initial bidder - **or set to address(0) if there is not a true initial bidder.**
- In the internal auction contract code l.initialBidder actually applies to the previous bidder.  (**Or the 0 address if there has not been a previous bidder**).  Perhaps the diamond storage variable can be renamed previousBidder for clarity.

**Comment by gravenp** [comment]
Artist/Owner is trusted and responsible for setting the initialBidder. It is NOT EXPECTED to be set to zero from a logical business perspective but is currently allowed in the code. The team agrees that it would be a good idea to set a check for this. Based on the trusted role and Sherlock rules about 0 address checks, I believe this would be a low-severity item.

**Comment by 14si2o** [comment]
I'm happy you will fix it since the impact is Critical.
 
I do not agree with the Low severity classification. You state that initialBidder is not expected to b e zero from a logical business perspective. This is incorrect. 

When there is no initialBidder, address(0) is the only logical input. As your colleague @St4rgarden clearly stated above. What other logical input can be expected when there is no initial bidder? 

Example Auction X by Owner Alice with no initial bidder. 
What are possible expected values for `initialBiddder`? 

- address(0) since there is no initial bidder. 
- ???

For this finding to be invalid, you would have to make the argument that an owner can be LOGICALLY expected to put his OWN address as initialBidder when there is no initial bidder, since that is the only case in which he would not lose all the money from the auction. There is no reason why he would ever do this. Nor is there anything from a code, documentation or historical perspective that would give any support to that argument. 

When the owner starts an auction for a new collection and there is no initial bidder, then the EXPECTED, LOGICAL input is address(0) for initialBidder. Since there is no initialBidder. 

Concerning the Sherlock [Rules](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid)

- Zero address checks: Check to make sure input values are not zero addresses.
- Admin incorrectly enters an input parameter.

The first rule about Zero address checks concerns cases of implementing checks where wrongfully inputting address(0) would lead to a problem. For example setting the address of "owner" or "recipient" to address(0). In **this case**, any owner will logically want to set address(0) when there is no initial bidder, so implementing a zero address check would actually break the protocol.  

The second rule about incorrect input concerns cases where the admin mistypes an address or an amount. In **this case**, setting address(0) to initialBidder cannot be considered incorrect input, since it is the logical choice and there is no reasonable other input when there is no initial bidder. 

As such, this finding cannot be downgraded based upon these rules. So I believe this to be a valid High finding. 

I rest my case here and I will leave it to the Head of Judging to make his evaluation.

**Comment by gravenp** [comment]
I'm sorry that I didn't catch the parentheticals in that comment in Discord which have led to this misunderstanding.

I can state with 100% certainty from a business logic perspective that the `initialBidder` address wasn't intended to be set to 0--hence the fix is to set a 0 check to prevent it. When creating a collection from the UI, the `initialBidder` address is automatically set to the artist/creator's address. This field doesn't strictly require that you be a "bidder."

We are going to make a change, appreciate your submission, and ultimately aren't concerned with the final labeling, but simply tried to provide the proper context for the judges to make their evaluation.

**Comment by 14si2o** [comment]
Thank you for your remarks @gravenp. 

I understand the situation better. We are talking about two different groups of users. 

You refer to the group of users who are interacting with the protocol through the web UI. For them, setting initialBidder to address(0) is certainly not expected and, given your explanation, even impossible since it will be set automatically. 

I refer to the group of more advanced users who will directly interact with the protocol by calling the external functions on-chain. For this group, the business logic deviates from the first group since they must set all the parameters (under which initialBidder) manually. The statement of your colleague @St4rgarden concerning setting address(0) should be seen in the context of this group I believe.     


For the first group, as you explained, this finding is not an issue since they do not have the option to manually set the initialBidder variable. 

However, for the second group, when they are initializing an auction through a call to `initializeAuction`, they **must** provide a value for `initialBidder`. And in the case where there is no initial bidder, as I've argued above, setting address(0) is the only logical choice. There is nothing in the code or NatSpec that would give the user any indication that he needs to put himself as initialBidder in order not to lose the proceedings of the auction in an edge case. 

The assumption that the business logic for the first group can be applied to the second fails due to the divergent set of actions available to the members of the groups. While the first cannot set the bidder variable, the second **must** set it to initialize an auction. And in such a case, setting it to 0 when there is no bidder becomes the normal and logical behavior.  As such, I maintain my position that this is indeed a valid High since it flows forth from normal on-chain interaction with the protocol. 


### In regards to mitigation, I would argue **against** the implementation of a zero-address check. 

For the first group of users there is no need since they cannot set the initialBidder. 
For the second group however, this will leads to a large amount of reverts and confused and frustrated users. 

Assume user A wants to initialize an auction for his new collection by calling the external function. He provides all the necessary parameters, for `initialBidder` he sets address(0) since there is no initial bidder and he executes the call. To his surprise the call reverts with the "InitialBidder cannot be address(0)". This is very confusing and illogical, there is no initial bidder so there is no valid address he can set. There is nothing in code nor natspec that would indicate what `initialBidder `is supposed to be if there isn't one. 

As a consequence, user A is either forced to directly contact the protocol team to find out what he should do, or and most likely, he will assume the code is broken and wont interact anymore with the protocol for fear of losing his money. 

Instead, I would propose to accept address(0) for the valid input that it is and simply add an if statement to set initialbidder to repossessor whenever the user indicates there is no initial bidder. 

in  `_initializeAuction`
```solidity 
if(initialBidder == address(0)) {
    l.initialBidder = repossessor;
}


```

**Comment by gravenp** [comment]
There are expected business scenarios where the artist would want the `initialBidder` (which can be understood better as the *Initial Steward* at initialization) to be different than the `repossessor`. For example, holding an offline auction to launch a piece before bringing it onchain with that auction winner as the initial steward. I'm comfortable with not accepting a 0 address for this field and will leave it at that.

**Comment by zzykxx** [comment]
This should stay invalid, it's responsability of the artist to set a correct `initialBidder`. Furthermore there is nothing special about the `address(0)` address, an artist setting the `initialBidder` to `address(1)` also leads to the same outcome and the same argument can be made for any other address of which a private key is not known.

**Comment by 14si2o** [comment]
@zzykxx 

Indeed an artist needs to set a correct `initialBidder`, otherwise he can't initialize an auction. 

So when there is no `initialBidder`, which is a common occurrence, what then are the possible correct and incorrect inputs? 

The protocol dev I quoted in the finding stated that in such a case, the correct input should be  `address(0)`. The function natspec & code also give no other reasonable alternative. So if that input is correct, then I believe the finding is valid since an artist would lose money from a correct input.  

If not, which I believe you're alluding to in your comment, then what is the correct input?

What value would an artist deem to be correct when there is no initialBidder? I & the protocol dev are of the opinion that there is no logical alternative than address(0). 

Otherwise, would he have to magically divine that his own address is the only correct input instead of the logical input?

**Comment by ghost** [comment]
I agree with @zzykxx reasoning that its admin responsibility to set correct `initialbidder` thus it should be considered as low finding.

**Comment by gravenp** [comment]
As @zzykxx & @Hash01011122 are aligned, this may be necessary, but let me be 100% clear for @14si2o: we ALWAYS expect the admin to set a valid `initialBidder` address. Not having an address here is not "a common occurrence" or intended. We will make sure that this expectation and the meaning of "Initial Bidder" at initialization is well documented.

**Comment by 14si2o** [comment]
@St4rgarden I've seen that you've been answering escalations, would it be possible to give your input? 

The entire finding rests for a large part on your initial comment in general discord.

**Comment by gravenp** [comment]
@14si2o as I've stated previously, St4rgarden misspoke in the Discord in that message. He wasn't the original dev that wrote this code and was answering questions quickly. Again, my previous comment is the team's official stance.

**Comment by Czar102** [comment]
@gravenp @Hash01011122 Was there truly no documentation regarding the need to set the `initialBidder`, even in the form of comments in code? I can see how the message could be a mistake, but we would need any signal from the code/code comments/documentation/other messages that imply this.

@14si2o there is no need to further elaborate on this issue unless tagged.

**Comment by gravenp** [comment]
@Czar102, the blue info box on this [doc page](https://pco-art-docs.vercel.app/for-artists/auction-pitches) references the Arist as "...the default 'previous Steward'" and the default recipient of the initial auction proceeds (and how to set change this recipient to someone else). Functionally this means setting this `initialBidder` field to the artist address instead of 0. This is how it is implemented on the reference UI as well.

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is.

Agree with the artist responsibility reasoning.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ABDUullahi](https://github.com/sherlock-audit/2024-02-radicalxchange-judging/issues/28/#issuecomment-2024952233): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/RadicalxChange/pco-art/pull/15

**Comment by zzykxx** [comment]
The issue has been fixed by requiring the `initialBidder` address to be non-zero on initialization.

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
